# Generated by Django 4.1.5 on 2023-01-08 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultation',
            name='comments',
            field=models.TextField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='meeting_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='reason',
            field=models.TextField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='currency',
            field=models.CharField(blank=True, default='CAD', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='payment_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='name',
            field=models.CharField(max_length=30),
        ),
    ]
